stages:
- plan
- apply

default:
  image: hashicorp/terraform:1.16.1
  before_script:
    - terraform --version

.azure_login:
  before_script:
    - apk add --no-cache bash curl jq python3
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash

    # Login to Azure using GitLab's OIDC token
    - az login --service-principal
        --username "$AZURE_CLIENT_ID"
        --tenant "$AZURE_TENANT_ID"
        --federated-token "$GITLAB_OIDC_TOKEN"
        --service-principal

    - az account set --subscription "$AZURE_SUBSCRIPTION_ID"

.terraform_init:
  before_script:
    - >
      terraform init
      -backend-config="resource_group_name=${TF_VAR_resource_group_name}"
      -backend-config="storage_account_name=tfstatestorageacc4562"
      -backend-config="container_name=tfstate"
      -backend-config="key=terraform.tfstate"

terraform_plan:
  stage: plan
  extends:
    - .azure_login
    - .terraform_init
  script:
    - terraform plan -out=tfplan -input=false
  artifacts:
    paths:
      - tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

terraform_apply:
  stage: apply
  extends:
    - .azure_login
    - .terraform_init
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'