- name: kubeadm init
  hosts: localhost
  connection: local
  gather_facts: yes
  become: true

  tasks:
    - name: Install container runtime
      import_role:
        name: containerd
    
    - name: Install kubeadm using role
      import_role:
        name: kubeadm
  
- name: Init control plane
  hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  tasks:
    - name: kubeadm init
      ansible.builtin.shell:
        cmd: kubeadm init --pod-network-cidr=192.168.0.0/16 --kubernetes-version "{{ k8s_release_version }}"
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init
      changed_when: kubeadm_init.rc == 0
    
    - name: Create .kube directory
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: true
        mode: "0644"
        owner: "{{ ansible_user }}"

    - name: Get join command
      ansible.builtin.shell:
        cmd: kubeadm token create --print-join-command
      register: join_command
      changed_when: false
    
    - name: Allow all access to tcp port 6443
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp