name: terraform apply
on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    env:
      TF_VAR_resource_group_name: ${{ vars.TF_RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.1

      - name: Terraform Init
        run: make tf-init-backend

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download Terraform plan
        uses: actions/download-artifact@v7
        with:
          name: tfplan

      - name: Terraform apply
        run: terraform apply tfplan -auto-approve