name: terraform plan
on:
  pull_request:
    branches:
      - main
    types:
     - opened
     - synchronize
     - reopened

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_CLI: "false"
      TF_IN_AUTOMATION: "true"
      TF_VAR_resource_group_name: ${{ vars.TF_RESOURCE_GROUP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.16.1

      - name: Check Azure credentials
        run: |
          test -n "$ARM_CLIENT_ID" && echo "ARM_CLIENT_ID is set"
          test -n "$ARM_CLIENT_SECRET" && echo "ARM_CLIENT_SECRET is set"
          test -n "$ARM_TENANT_ID" && echo "ARM_TENANT_ID is set"
          test -n "$ARM_SUBSCRIPTION_ID" && echo "ARM_SUBSCRIPTION_ID is set"

      - name: Terraform Init
        run: make tf-init-backend

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
